# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00acc71cc4a9ebda96c2ebab615a1358"
name = "c&c"
handle = "c-c"
application_url = "https://crm-fail-neo-signatures.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saasintegrator-click-collect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_discounts,read_inventory,read_locales,read_locations,read_metaobjects,read_product_listings,read_products,read_script_tags,read_shipping,write_content,write_discounts,write_inventory,write_locales,write_locations,write_metaobjects,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://crm-fail-neo-signatures.trycloudflare.com/auth/callback",
  "https://crm-fail-neo-signatures.trycloudflare.com/auth/shopify/callback",
  "https://crm-fail-neo-signatures.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
