# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2aef3cf60c016454d3da1bc06566b9e"
name = "clickncollect"
handle = "clickncollect-1"
application_url = "https://clickncollect-12d7088d53ee.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "saas-click-collect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_locations,read_orders,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://clickncollect-12d7088d53ee.herokuapp.com/auth/callback",
  "https://clickncollect-12d7088d53ee.herokuapp.com/auth/shopify/callback",
  "https://clickncollect-12d7088d53ee.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[app_preferences]
url = "https://clickncollect-12d7088d53ee.herokuapp.com/"
