# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0acbe1ea218ca74db8c10d1234659d6"
name = "clickncollectnew"
handle = "clickncollectnew"
application_url = "https://recruiting-mars-singing-book.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saas-click-collect.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags"

[auth]
redirect_urls = [
  "https://recruiting-mars-singing-book.trycloudflare.com/auth/callback",
  "https://recruiting-mars-singing-book.trycloudflare.com/auth/shopify/callback",
  "https://recruiting-mars-singing-book.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
