# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "599e38a5b5f504f91478a174bb336da3"
name = "C&C-N"
handle = "c-c-n"
application_url = "https://clothing-workforce-intent-because.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "deepakb2b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping,read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags"

[auth]
redirect_urls = [
  "https://clothing-workforce-intent-because.trycloudflare.com/auth/callback",
  "https://clothing-workforce-intent-because.trycloudflare.com/auth/shopify/callback",
  "https://clothing-workforce-intent-because.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
