# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "259171835da6db9367118d079b818e76"
name = "click-collect-PDP"
handle = "click-collect-pdp"
application_url = "https://dna-underground-brand-strengthening.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "deepakb2b.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping,read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags"

[auth]
redirect_urls = [
  "https://dna-underground-brand-strengthening.trycloudflare.com/auth/callback",
  "https://dna-underground-brand-strengthening.trycloudflare.com/auth/shopify/callback",
  "https://dna-underground-brand-strengthening.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
